services:
  client:
    image: node:20
    restart: unless-stopped
    volumes:
      - ./client:/usr/src/client
    ports:
      - "80:80"
    command: sh -c "/usr/src/client/startup.sh"
  server:
    image: node:20
    restart: unless-stopped
    volumes:
      - ./server:/usr/src/server
    ports:
      - "8080:8080"
      - "6436:6436"
    command: sh -c "/usr/src/server/startup.sh"
